### ISSUE TITLE
[1.10.2] ChickensMod Spawner from EnderIO produces random varient chicken

### ISSUE THREAD

**Issue by Morpheus1101** [setycz/ChickensMod#37]
So i went and got the Awakened Draconium Chicken and multiplied the heck out of them, but its not producing the nuggets fast enough, so i went and captured one in a Soul Vial and made a Spawner from EnderIO ... however once hooked up, it spawns Random variants from the entire list rather than the specific Chicken i had captured

**Comment by GenDeathrow** [comment]
@Morpheus1101 its because spawner's don't save nbt data if I am not mistaken.  but [Mob Grinding Utils](https://minecraft.curseforge.com/projects/mob-grinding-utils?gameCategorySlug=mc-mods&projectID=254241) has a method with the Swab. Also [hatchery ](https://minecraft.curseforge.com/projects/hatchery) will have a device (**not yet next update**)that can  sort babys from adults that you could than kill, and use hatchery feeder to make them grow up faster.
