### ISSUE TITLE
JEI error w/ more chickens

### ISSUE THREAD

**Issue by GenDeathrow** [setycz/ChickensMod#64]
#### Issue Description:
Jei recipes dont work with latest version of because of a me derp. I forced some special chickens to a specfic tier and removed the parents.. with out realizing that the chickens jei plugin looks for chickens over tier 1.. and assumes it has parents.  Im leaving this as a note for anyone that may try to report theissue here.

**Comment by GenDeathrow** [comment]
https://github.com/GenDeathrow/Hatchery/issues/40#issuecomment-272247599

**Comment by GenDeathrow** [comment]
https://github.com/setycz/ChickensMod/pull/65

**Comment by setycz** [comment]
I wonder how could you force some chicken to specific tier without it having parents? ;] Tier is calculated from [hiearchy](https://github.com/setycz/ChickensMod/blob/1.10.2/src/main/java/com/setycz/chickens/ChickensRegistryItem.java#L96) . So I don't know how your pull request could help because getTier() already checks for parents not being null, if any parent is null then tier is 1. Could you explain it please? ;]

**Comment by setycz** [comment]
See changes 71c83b69639efce70d9937cd7c84df192d2d2ee2 , I have released 4.3.1 with the new API. Sorry for late reaction time, but I was not at home ;]. Let me know if it helped you.

**Comment by GenDeathrow** [comment]
Sorry forgot to respond this was a perfect addition to the api. Works as intended.
