### ISSUE TITLE
Add breeding guide to README or Mod Page

### ISSUE THREAD

**Issue by didymusbenson** [setycz/ChickensMod#83]
A few months ago I wrote this guide providing a simple explanation for how to breed chickens in this mod and "More Chickens." This is a resource I would have liked to have had the first time I played using the mod, as the NEI gui was confusing (and I wanted to see more recipes at once). The guide can be found below and I'm perfectly fine with you pulling the tables out and adding them to your readme/mod page.

https://www.reddit.com/r/feedthebeast/comments/5r1zxs/chickens_breeding_guide/

**Comment by GenDeathrow** [comment]
Breeding guides can be different from pack to pack. even some mods added in will change what chickens parents are. I have an idea for a better in-game tree to show parents. instead of the current system. but it may be a bit of time to get it finished. 

With that said.. there is already a sort of breading guide that gets generated.. in logs/chickens.gml. You just need a program like Gephi to read it. Not the most intuitive thing but it does give you an outline.
