### ISSUE TITLE
Chickens on a Skyfactory 3 server.

### ISSUE THREAD

**Issue by Jamm22** [setycz/ChickensMod#94]
Hello,

I own a Skyfactory 3 server.

I get around 15+ players online at the same time.

I dont have limits for chickens as of now.

Although I would like to see a option in the future for this mod to make chickens maybe player connected, 
what I mean by this is that chickens will get registered under a player.
In this way server owners can limit the amount of chickens a player can own.
Definitely try to make this possible, every server owner will thank you forever.

Other problem.

At some point my server clears 2000+ entities per clear.
this went from 12 to 2000 in 3 days..

I looked up where the most entities spawned, they spawned at 0, 0, 0.
When I went to that location my inventory immediately filled up with items.
The problem is that there is massive item dropping from chickens there, but I cant even see the chickens so I cant kill them.

Would like to get some more info and troubleshooting on this, since I dont want to destroy the chicken fun on my server by disabling the mod.

-Jamm.

**Comment by GenDeathrow** [comment]
What type of server are you running?

**Comment by Jamm22** [comment]
FTB Skyfactory 3 on Sponge.

**Comment by GenDeathrow** [comment]
Sponge is the problem, I have had other ppl report this issue, they have all been using Sponge. It isn't the first Sponge related issue and probably wont be the last.

**Comment by GenDeathrow** [comment]
I believe this is also related to Hatchery and Sponge (Not Chickens Mod).. Sponge doesn't seem to like my other mod.

**Comment by Jamm22** [comment]
As always.. 

Sponge hasn't been the nicest to server owners..

Any suggestions / tips on 'trying' to solve it?

**Comment by GenDeathrow** [comment]
The real answer is don't use sponge, There are other mods out their to accomplish what you need most of the time. Mod devs write for Forge, Sponge piggy backs off of forge, and well they are suppose to be supporting it, but they are rewriting key features in forge that us devs use. IE, My nesting pens use a forge method, that sponge ignores completely, which, makes items drop outside of the nesting pens, or apparently at 0,0,0 now. I will not support Sponge because one they dont have a similar method, and two they keep breaking my mod and others with each update.

**Comment by GenDeathrow** [comment]
I apologize if it sounds like a rant, but I have been trying to get them to fix these issues for the last 5-6 months now. And from the recent issues, I think they broke my mod even worst.

Edit: The only other thing you can do is remove Hatchery that should fix the issue. but everyone will need to remove their chickens first or you will lose them all.

**Comment by Jamm22** [comment]
It's just a waste to see mods being broken by sponge..

Issue: https://www.youtube.com/watch?v=FpaAWz01AQA&feature=youtu.be

Kinda solved there.

**Comment by sarim-aeyzaz** [comment]
Hi, sorry for replying to a closed and old issue but the video is unavailable unfortunately. I seem to have this issue aswell on the server I play on but I was wondering if you could hint me on how to fix this. We're planning to release a server soon but this issue may end up annoying us in the long-term but unfortunately, we can't opt out of sponge due to other reasons, thanks in advance :).

**Comment by Jamm22** [comment]
I remeber using a trashcan and a proximity hopper on it.
